name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
    - run: cd JoyStickView && xcodebuild build-for-testing -scheme JoyStickView -destination "platform=iOS Simulator,OS=latest,name=iPhone 12"
    - name: Tests
    - run: cd JoyStickView && xcodebuild test-without-building -scheme JoyStickView -destination "platform=iOS Simulator,OS=latest,name=iPhone 12"
    - name: View Tests
    - run: xcodebuild test -destination 'name=iPhone 11' -scheme 'JoyStickView App'
