name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run monitor tests
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'JoyStickView'
    - name: Run view tests
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'JoyStickView App'
